# Workflow for verifying bikeshed documents processing

name: Verify processing
on:
  # only concerned with gating PRs to the main branch
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Bikeshed
        run: |
          pipx install bikeshed
          bikeshed update

      - name: Generate HTML
        run: for bsdoc in ./*.bs; do bikeshed spec --gh-token=${{ secrets.GITHUB_TOKEN }} $bsdoc; done

      - name: Generate SVG
        run: for diagram in ./*.mmd; do docker run --rm -v "$PWD:/data" minlag/mermaid-cli -i /data/$diagram; done
